server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus_second_hand?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: "051010"
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.secondhand.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.secondhand.mapper: debug